[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "parkinsons"
version = "0.1.0"
dependencies = [
  "scikit-learn",
  "pandas",
  "fastapi",
  "uvicorn"
]

[tool.setuptools.packages.find]
where = ["src"] 
